reporter-option:
 - 'reportDir=artifacts/mochawesome-report/'
 -  quiet=true
 -  overwrite=false
 -  html=true
 -  json=true
 -  timeOut=false
 -  timestamp=HHMM_ddmmyyyy
recursive: true
require:
  [
    'ts-node/register',
    'mocha',
    'chai/register-expect',
  ]
extension: [ts]
timeout: 10000
retries: 1
inline-diffs: true
watch-files:
  - 'test/**/*.ts'
